from pathlib import Path
# daily scheduler: add subject batch helper before export default and branch
p=Path('/mnt/data/work/server/api/daily-scheduler.js'); s=p.read_text()
marker='export default async function handler(req, res) {'
assert marker in s
helper=r'''
async function runSubjectBatchJob({ sb, gemini, subject, target = 100, jobKey, retryOptions = {} }) {
  const safeTarget = Math.min(Math.max(Number(target || 100), 1), 100);
  if (!gemini) return { ok: false, error: 'Gemini AI is not configured', subject, target: safeTarget, inserted: 0, rejected: 0 };
  const accepted = [];
  const seen = new Set();
  let rejected = 0;
  let rounds = 0;
  const maxRounds = 18;

  const existingHashes = new Set();
  if (sb) {
    try {
      const { data } = await sb.from('questions').select('content_hash').eq('subject', subject).not('content_hash', 'is', null).limit(10000);
      for (const row of data || []) if (row.content_hash) existingHashes.add(row.content_hash);
    } catch (_) {}
  }

  while (accepted.length < safeTarget && rounds < maxRounds) {
    rounds++;
    const need = Math.min(20, safeTarget - accepted.length);
    let generated = [];
    try {
      generated = await generateGeminiQuestionsForSubject(gemini, subject, need, retryOptions);
    } catch (err) {
      rejected += need;
      if (err?.isQuotaExhausted) break;
      continue;
    }
    if (!generated.length) { rejected += need; continue; }

    for (const raw of generated) {
      if (accepted.length >= safeTarget) break;
      const gq = resolveOptionDuplicatesAndDistribute(raw || {});
      const record = {
        question: gq.question,
        question_hi: gq.question_hi || null,
        option_a: gq.option_a,
        option_b: gq.option_b,
        option_c: gq.option_c,
        option_d: gq.option_d,
        option_a_hi: gq.option_a_hi || null,
        option_b_hi: gq.option_b_hi || null,
        option_c_hi: gq.option_c_hi || null,
        option_d_hi: gq.option_d_hi || null,
        correct_answer: gq.correct_answer,
        explanation: gq.explanation || '',
        explanation_hi: gq.explanation_hi || null,
        subject,
        topic: gq.topic || 'Syllabus Standard',
        difficulty: gq.difficulty || 'Moderate',
        language: gq.question_hi ? 'English + Hindi' : 'en',
        exam: 'Daily AI Question Bank',
        status: 'pending_review',
        ai_review_status: 'pending_review',
        ai_notes: 'Generated by daily subject-wise Gemini batch; requires AI/admin validation before publication',
        daily_job_key: jobKey
      };
      const val = validateQuestionDeterministic(record);
      if (!val.valid) { rejected++; continue; }
      if (subject === 'Mathematics' && isSubjectStrictMatch(record.subject, 'Reasoning')) { rejected++; continue; }
      if (subject === 'Reasoning' && isSubjectStrictMatch(record.subject, 'Mathematics')) { rejected++; continue; }
      const hash = crypto.createHash('sha256').update(`${normalizeText(record.question)}:${normalizeText(record.option_a)}:${val.cleanedAnswer}`).digest('hex');
      if (seen.has(hash) || existingHashes.has(hash)) { rejected++; continue; }
      seen.add(hash);
      existingHashes.add(hash);
      record.correct_answer = val.cleanedAnswer;
      record.content_hash = hash;
      accepted.push(record);
    }
  }

  let inserted = 0;
  if (sb && accepted.length) {
    for (let i = 0; i < accepted.length; i += 25) {
      const chunk = accepted.slice(i, i + 25);
      const { data, error } = await sb.from('questions').insert(chunk).select('id');
      if (!error) inserted += (data || []).length;
      else console.warn(`[Subject Batch Insert Warning] ${subject}:`, error.message);
    }
  }
  return { ok: inserted === safeTarget, subject, target: safeTarget, inserted, rejected, rounds, remaining: Math.max(0, safeTarget - inserted), status: inserted === safeTarget ? 'complete' : 'partial' };
}

'''
s=s.replace(marker,helper+marker,1)
# branch after auth and before normal today config; find authorization close then let todayStr
needle="  let logRecordId = null;\n\n  try {\n"
assert needle in s
branch=r'''  // Subject-wise 100-question worker. Each subject is intentionally a separate request
  // so one failed/slow subject does not block the rest of the daily pipeline.
  const requestBody = sanitizeObject(req?.body || {});
  const subjectBatch = sanitizeString(requestBody.subject || '', 80);
  if (requestBody.mode === 'subject_batch' && subjectBatch) {
    if (!sb) return res ? res.status(500).json({ ok: false, error: 'Database server configuration unavailable' }) : { ok: false, error: 'Database unavailable' };
    const gemini = getGeminiClient();
    const result = await runSubjectBatchJob({
      sb,
      gemini,
      subject: subjectBatch,
      target: requestBody.target || 100,
      jobKey: sanitizeString(requestBody.jobKey || `subject_${subjectBatch}_${getKolkataDateString()}`, 120),
      retryOptions: { timeoutMs: 25000, maxRetries: 3, initialDelayMs: 1200 }
    });
    return res ? res.status(result.ok ? 200 : 207).json(result) : result;
  }

  let logRecordId = null;

  try {
'''
s=s.replace(needle,branch,1)
# export helper
s=s.replace('  loadLocalSeedQuestions\n};','  loadLocalSeedQuestions,\n  runSubjectBatchJob\n};')
p.write_text(s)

# current affairs: add Gemini research helper and call when researchSixMonths true
p=Path('/mnt/data/work/server/api/sync-current-affairs.js'); s=p.read_text()
marker='export default async function handler(req, res) {'
assert marker in s
helper=r'''
async function researchSixMonthsWithGemini(gemini, sb, jobKey) {
  if (!gemini || !sb) return { added: 0, researched: 0, error: 'Gemini or database unavailable' };
  const prompt = `Use Google Search grounding to research the last 6 months of exam-relevant current affairs for India and Madhya Pradesh as of today. Cover national and international developments, summits, expos, conferences, awards, appointments, government schemes, economy, banking/RBI/SEBI, defence, science/technology/space, sports, environment, reports/indexes, books/authors, important days, major organizations and important MP state events. Prioritize facts that are likely to appear in competitive exams (UPSC, MPPSC, MPESB, SSC, Banking, Railway).\n\nRules:\n- Search the web; do not rely only on model memory.\n- Prefer primary/official sources (government ministries, PIB, RBI, SEBI, ISRO, UN, official event sites, MP government/MPPSC/MPESB) and reputable sources for context.\n- Do not invent facts, dates, numbers or names.\n- Return up to 80 distinct factual items, spread across categories and months.\n- Each item must have a title, concise summary, event_date (YYYY-MM-DD when known), category, source_name and source_url.\n- Return JSON only: {"items":[{"title":"...","summary":"...","event_date":"YYYY-MM-DD","category":"...","source_name":"...","source_url":"https://..."}]}`;
  const response = await callGeminiWithRetry(
    () => gemini.models.generateContent({
      model: getNormalizedGeminiModel(process.env.GEMINI_REVIEW_MODEL_ID),
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: { responseMimeType: 'application/json', tools: [{ googleSearch: {} }] }
    }),
    { operationName: 'Gemini Six-Month Current Affairs Research', timeoutMs: 45000, maxRetries: 3, initialDelayMs: 1500 }
  );
  const parsed = cleanJsonParse(response.text || '{}');
  const items = Array.isArray(parsed.items) ? parsed.items : [];
  let added = 0;
  for (const item of items.slice(0, 80)) {
    const title = String(item.title || '').trim();
    const summary = String(item.summary || '').trim();
    const sourceUrl = String(item.source_url || '').trim();
    if (!title || !summary || !/^https?:\/\//i.test(sourceUrl)) continue;
    const externalId = `gemini6m:${crypto.createHash('sha256').update(`${title}|${sourceUrl}`).digest('hex')}`;
    const { data: existing } = await sb.from('current_affairs').select('id').eq('external_id', externalId).maybeSingle();
    if (existing) continue;
    const eventDate = /^\d{4}-\d{2}-\d{2}$/.test(String(item.event_date || '')) ? String(item.event_date) : new Date().toISOString().slice(0,10);
    const { error } = await sb.from('current_affairs').insert({
      external_id: externalId,
      title: title.slice(0,280),
      summary: summary.slice(0,1800),
      source_name: String(item.source_name || 'Gemini web research').slice(0,120),
      source_url: sourceUrl,
      category: String(item.category || 'General Current Affairs').slice(0,120),
      subject: 'Current Affairs',
      topic: String(item.category || 'General Current Affairs').slice(0,120),
      published_at: new Date(`${eventDate}T00:00:00Z`).toISOString(),
      event_date: eventDate,
      generated_at: new Date().toISOString(),
      verification_status: 'gemini_web_researched_pending_review',
      source_metadata: { research_window: 'last_6_months', job_key: jobKey, grounded_by: 'Google Search' },
      status: 'published',
      question_count: 0
    });
    if (!error) added++;
  }
  return { added, researched: items.length };
}

'''
s=s.replace(marker,helper+marker,1)
# extend destructuring
s=s.replace('      createQuiz = false,\n      jobKey = null','      createQuiz = false,\n      researchSixMonths = false,\n      jobKey = null')
# insert research after real official bulletins before question generation
needle='    // 2. Question Generation (STRICT TRACEABILITY)\n'
assert needle in s
insert="    let aiResearchAdded = 0;\n    let aiResearchCount = 0;\n    if (researchSixMonths) {\n      try {\n        const research = await researchSixMonthsWithGemini(gemini || getGeminiClient(), sb, effectiveJobKey);\n        aiResearchAdded = research.added || 0;\n        aiResearchCount = research.researched || 0;\n      } catch (researchErr) {\n        console.warn('[Gemini 6M Current Affairs Research Warning]:', researchErr.message);\n      }\n    }\n\n"
s=s.replace(needle,insert+needle,1)
# gemini variable currently declared after research insertion, so we referenced gemini before declaration. Move declaration earlier.
# Replace section declaration to define gemini before research.
s=s.replace("    // 2. Question Generation (STRICT TRACEABILITY)\n    // Questions are ONLY generated if real official source bulletins exist\n    // Never invent facts, dates, figures or schemes.\n    const isGeminiEnabled", "    // 2. Question Generation (STRICT TRACEABILITY)\n    // Questions are ONLY generated if real official source bulletins exist\n    // Never invent facts, dates, figures or schemes.\n    const gemini = req.geminiClient || getGeminiClient();\n    const isGeminiEnabled")
s=s.replace("    const gemini = req.geminiClient || getGeminiClient();\n    let generatedQuestionCount", "    let generatedQuestionCount")
# include research counts in response/log message
s=s.replace("      message: `Current Affairs & Recruitment Portals sync completed: ${addedAffairs} new official bulletins ingested (${insertedAffairs.length} active in bank), ${OFFICIAL_RECRUITMENT_PORTALS.length} recruitment portals verified, ${generatedQuestionCount} questions drafted.`,", "      message: `Current Affairs sync completed: ${addedAffairs} official bulletins + ${aiResearchAdded} Gemini web-researched 6-month items; ${generatedQuestionCount} questions drafted.`,")
s=s.replace("        recruitment_portals_count: OFFICIAL_RECRUITMENT_PORTALS.length,", "        ai_research_6_months: Boolean(researchSixMonths),\n        ai_research_items_found: aiResearchCount,\n        ai_research_items_added: aiResearchAdded,\n        recruitment_portals_count: OFFICIAL_RECRUITMENT_PORTALS.length,")
s=s.replace("      questions_drafted: generatedQuestionCount,", "      questions_drafted: generatedQuestionCount,\n      ai_research_6_months: Boolean(researchSixMonths),\n      ai_research_items_found: aiResearchCount,\n      ai_research_items_added: aiResearchAdded,")
p.write_text(s)
