import React,{useState,useEffect} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,BookOpen,ClipboardCheck,Search,Settings,LogOut,Clock3,Upload,Users,PlusCircle,Menu,X} from "lucide-react";
import "./styles.css";
const exams=[
{name:"IBPS RRB PO",cat:"Banking",tag:"TRENDING",q:80,time:"60 min"},
{name:"MPESB Sub Engineer",cat:"MP",tag:"TRENDING",q:100,time:"120 min"},
{name:"MP SI",cat:"MP Police",tag:"TRENDING",q:100,time:"120 min"},
{name:"MP Police Constable",cat:"MP Police",tag:"TRENDING",q:100,time:"120 min"},
{name:"RRB NTPC",cat:"Railway",tag:"POPULAR",q:100,time:"90 min"},
{name:"SSC CGL",cat:"SSC",tag:"POPULAR",q:100,time:"60 min"}];
const subjects=["Mathematics","Reasoning","General Awareness","Banking Awareness","English","Hindi","Computer","General Science","MP GK"];
function App(){
 const [role,setRole]=useState("student"),[logged,setLogged]=useState(false),[page,setPage]=useState("dashboard"),[open,setOpen]=useState(false),[selected,setSelected]=useState(null);
 if(!logged)return <Landing role={role} setRole={setRole} open={open} setOpen={setOpen} login={()=>setLogged(true)}/>;
 return <Shell role={role} page={page} setPage={setPage} logout={()=>setLogged(false)} selected={selected} setSelected={setSelected}/>;
}
function Landing({role,setRole,open,setOpen,login}){
 return <div className="landing"><header className="topbar"><div className="brand"><span className="logo">E</span><div><b>ExamVerse</b><small>Prepare Smart. Perform Better.</small></div></div><div className="top-actions"><button className="btn ghost" onClick={()=>{setRole("student");setOpen(true)}}>Student Login</button><button className="btn dark" onClick={()=>{setRole("admin");setOpen(true)}}>Admin</button></div></header><main className="hero"><div className="hero-copy"><span className="pill">SMART EXAM PREPARATION</span><h1>Practice like the real exam.</h1><p>Subject-wise practice, exam-wise mocks, live exams and performance analytics — all in one simple portal.</p><div className="hero-buttons"><button className="btn primary" onClick={()=>{setRole("student");setOpen(true)}}>Start Preparing</button><button className="btn light" onClick={()=>{setRole("admin");setOpen(true)}}>Open Admin Console</button></div></div><div className="hero-card"><b>Today's Practice</b><div className="score">72%<small>overall score</small></div><div className="bars"><i style={{width:"72%"}}/><i style={{width:"88%"}}/><i style={{width:"51%"}}/></div><div className="mini-row"><span>Reasoning</span><b>88%</b></div><div className="mini-row"><span>Mathematics</span><b>51%</b></div></div></main><section className="feature-grid">{["Subject Practice","Real Exam Mocks","Trending Vacancies","Live Countdown","Bulk Question Upload","Performance Analytics"].map((x,i)=><div className="feature" key={x}><b>{x}</b><span>{["Practice only the subject you need.","Exam-style interface and timing.","Find official recruitment links.","Server-safe countdown and auto-submit.","TXT, CSV, PDF, Word and images.","Know your weak and strong areas."][i]}</span></div>)}</section><footer>© 2026 ExamVerse · Powered by <b>SKTech All Right Reaver</b></footer>{open&&<Login role={role} close={()=>setOpen(false)} login={login}/>}</div>}
function Login({role,close,login}){const[otp,setOtp]=useState("");return <div className="modal-bg"><div className="modal"><button className="close" onClick={close}><X/></button><span className="pill">{role==="admin"?"ADMIN CONSOLE":"CANDIDATE PORTAL"}</span><h2>{role==="admin"?"Admin Login":"Welcome back"}</h2><p className="muted">{role==="admin"?"Secure administrator access.":"Login with mobile OTP or Google."}</p><label>{role==="admin"?"Email":"Mobile Number"}</label><input placeholder={role==="admin"?"admin@example.com":"+91 XXXXX XXXXX"}/>{role==="student"?<><button className="btn primary full" onClick={()=>setOtp("123456")}>Get OTP</button><label>OTP</label><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Enter OTP"/></>:<><label>Password</label><input type="password" placeholder="Admin password"/></>}<button className="btn dark full" onClick={login}>Continue</button>{role==="student"&&<button className="btn google full" onClick={login}>Continue with Google</button>}<small className="muted center">Demo authentication — Supabase will be connected next.</small></div></div>}
function Shell({role,page,setPage,logout,selected,setSelected}){const nav=role==="admin"?[["dashboard","Dashboard",LayoutDashboard],["questions","Question Bank",BookOpen],["exams","Exam Management",ClipboardCheck],["vacancies","Vacancies",Search],["candidates","Candidates",Users],["settings","Settings",Settings]]:[["dashboard","Dashboard",LayoutDashboard],["subjects","Subject Practice",BookOpen],["exams","Mock Tests",ClipboardCheck],["vacancies","Vacancies",Search]];return <div className="app"><aside className="sidebar"><div className="side-brand"><span className="logo">E</span><b>ExamVerse</b></div><div className="role-badge">{role==="admin"?"ADMIN CONSOLE":"CANDIDATE PORTAL"}</div>{nav.map(([id,t,I])=><button className={"nav "+(page===id?"active":"")} key={id} onClick={()=>setPage(id)}><I size={18}/>{t}</button>)}<button className="nav logout" onClick={logout}><LogOut size={18}/>Logout</button></aside><div className="main"><header className="dashbar"><button className="hamb"><Menu/></button><div><b>{role==="admin"?"Administration":"Hello, Candidate"} 👋</b><small>{role==="admin"?"Control your entire exam platform.":"Keep practicing and improve your score."}</small></div><div className="avatar">{role==="admin"?"A":"S"}</div></header><div className="content">{page==="dashboard"&&<Dashboard role={role} setPage={setPage} setSelected={setSelected}/>} {page==="subjects"&&<Subjects setSelected={setSelected}/>} {page==="exams"&&<Exams setSelected={setSelected}/>} {page==="vacancies"&&<Vacancies/>} {page==="questions"&&<Questions/>} {page==="candidates"&&<Candidates/>} {page==="settings"&&<SettingsPage/>}{selected&&<MockModal exam={selected} close={()=>setSelected(null)}/>}</div><footer className="dash-footer">Powered by <b>SKTech All Right Reaver</b></footer></div></div>}
function Title({t,s}){return <div className="title"><h1>{t}</h1><p>{s}</p></div>}
function Dashboard({role,setPage,setSelected}){if(role==="admin")return <><Title t="Admin Dashboard" s="Everything under your control."/><div className="stats">{[["Question Bank","12,480","+320 this week"],["Candidates","3,842","+126 this week"],["Live Exams","4","2 running now"],["Mock Attempts","28,640","+1,240 this week"]].map(x=><div className="stat" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="two"><div className="panel"><div className="panel-head"><b>Quick Actions</b></div><div className="quick"><button onClick={()=>setPage("questions")}><Upload/>Bulk Upload Questions</button><button onClick={()=>setPage("exams")}><PlusCircle/>Create Exam</button><button onClick={()=>setPage("vacancies")}><Search/>Add Vacancy</button></div></div><div className="panel"><div className="panel-head"><b>Trending Exams</b></div>{exams.slice(0,4).map(e=><ExamRow e={e} onClick={()=>setSelected(e)} key={e.name}/>)}</div></div></>;return <><Title t="Your Dashboard" s="Choose what you want to practice today."/><div className="stats"><div className="stat"><small>Overall Score</small><strong>72%</strong><span>↑ 6% this month</span></div><div className="stat"><small>Tests Completed</small><strong>38</strong><span>5 this week</span></div><div className="stat"><small>Strong Subject</small><strong>Reasoning</strong><span>88% accuracy</span></div><div className="stat"><small>Needs Practice</small><strong>Mathematics</strong><span>51% accuracy</span></div></div><Title t="🔥 Trending Exams" s="Exam-style mocks based on current priorities."/><div className="exam-grid">{exams.slice(0,4).map(e=><ExamCard e={e} onClick={()=>setSelected(e)} key={e.name}/>)}</div><Title t="📚 Practice by Subject" s="Focus only on the subject you need."/><div className="subject-grid">{subjects.slice(0,6).map(s=><button className="subject-card" key={s}><b>{s}</b><span>Practice →</span></button>)}</div></>}
function ExamCard({e,onClick}){return <div className="exam-card"><div className="card-top"><span className="tag">{e.tag}</span><span>{e.cat}</span></div><h3>{e.name}</h3><p>{e.q} Questions · {e.time}</p><button className="btn dark full" onClick={onClick}>Start Mock</button></div>}
function ExamRow({e,onClick}){return <button className="exam-row" onClick={onClick}><div><b>{e.name}</b><small>{e.cat} · {e.q} Questions</small></div><span>Start →</span></button>}
function Subjects({setSelected}){return <><Title t="📚 Subject Practice" s="Select a subject and difficulty."/><div className="subject-grid all">{subjects.map(s=><div className="subject-card big" key={s}><b>{s}</b><span>Easy · Moderate · Hard</span><button className="btn dark" onClick={()=>setSelected({name:s+" Practice",q:25,time:"25 min",cat:"Subject Test"})}>Start Practice</button></div>)}</div></>}
function Exams({setSelected}){return <><Title t="📝 Mock Tests" s="Real-exam style practice with countdown and auto-submit."/><div className="filter"><input placeholder="Search exam..."/><button className="btn light">All Exams</button><button className="btn light">Trending</button></div><div className="exam-grid">{exams.map(e=><ExamCard e={e} onClick={()=>setSelected(e)} key={e.name}/>)}</div></>}
function Vacancies(){return <><Title t="🔎 Latest Vacancies" s="Official recruitment information and direct official links."/><div className="panel vacancy">{exams.map(e=><div className="vac-row" key={e.name}><div><b>{e.name}</b><small>{e.cat} · Check official notification</small></div><a href="https://www.google.com" target="_blank" rel="noreferrer">Official Website ↗</a></div>)}</div></>}
function Questions(){return <><Title t="📚 Question Bank" s="Manage and bulk-import questions."/><div className="upload-box"><Upload size={38}/><h2>Bulk Question Upload</h2><p>TXT · CSV · XLSX · PDF · DOCX · JPG · PNG</p><button className="btn primary">Choose File</button><small>AI classification: Subject · Topic · Difficulty · Exam mapping · Duplicate check</small></div><div className="panel"><div className="panel-head"><b>Recent Questions</b><span>12,480 total</span></div>{["Percentage question","Seating arrangement","RBI monetary policy","MP GK – History","Time & Work"].map((x,i)=><div className="question-row" key={x}><span>Q{i+1}</span><b>{x}</b><small>AI classified · Approved</small></div>)}</div></>}
function Candidates(){return <><Title t="👥 Candidates" s="Candidate accounts and performance overview."/><div className="panel">{["Candidate 001","Candidate 002","Candidate 003","Candidate 004"].map((x,i)=><div className="question-row" key={x}><span className="avatar sm">{i+1}</span><b>{x}</b><small>Tests: {12+i*4} · Score: {68+i*5}%</small></div>)}</div></>}
function SettingsPage(){return <><Title t="⚙ Settings" s="Platform configuration."/><div className="panel settings-list"><label>Platform Name<input value="ExamVerse" readOnly/></label><label>Tagline<input value="Prepare Smart. Perform Better." readOnly/></label><label>Footer<input value="Powered by SKTech All Right Reaver" readOnly/></label><label>Ad Policy<select><option>Education & general e-commerce only</option></select></label></div></>}
function MockModal({exam,close}){const[time,setTime]=useState(3599),[q,setQ]=useState(1);useEffect(()=>{const id=setInterval(()=>setTime(t=>Math.max(0,t-1)),1000);return()=>clearInterval(id)},[]);return <div className="modal-bg"><div className="mock"><div className="mock-head"><b>{exam.name}</b><strong><Clock3 size={18}/> {String(Math.floor(time/60)).padStart(2,"0")}:{String(time%60).padStart(2,"0")}</strong></div><div className="mock-body"><main><span className="pill">QUESTION {q}</span><h2>Which of the following is the correct answer for this demo question?</h2>{["Option A","Option B","Option C","Option D"].map(x=><label className="option" key={x}><input type="radio" name="q"/>{x}</label>)}<div className="mock-actions"><button className="btn light" onClick={()=>setQ(Math.max(1,q-1))}>Previous</button><button className="btn light">Mark for Review</button><button className="btn dark" onClick={()=>setQ(q+1)}>Save & Next</button></div></main><aside><b>Question Palette</b><div className="palette">{Array.from({length:Math.min(exam.q||25,30)},(_,i)=><button className={i+1===q?"sel":""} onClick={()=>setQ(i+1)} key={i}>{i+1}</button>)}</div><button className="btn primary full" onClick={close}>Submit Demo</button></aside></div></div></div>}
createRoot(document.getElementById("root")).render(<App/>);