import React,{useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {LayoutDashboard,BookOpen,ClipboardCheck,Search,Settings,LogOut,Clock3,Upload,Users,PlusCircle,Menu,X,ChevronDown,TrendingUp,Target,ShieldCheck,FileText,BarChart3,CalendarDays,Zap,ArrowUpRight,CheckCircle2} from "lucide-react";
import "./styles.css";

const exams=[
{name:"IBPS RRB PO",cat:"Banking",tag:"TRENDING",q:80,time:"60 min"},
{name:"MPESB Sub Engineer",cat:"MP",tag:"TRENDING",q:100,time:"120 min"},
{name:"MP SI",cat:"MP Police",tag:"TRENDING",q:100,time:"120 min"},
{name:"MP Police Constable",cat:"MP Police",tag:"TRENDING",q:100,time:"120 min"},
{name:"RRB NTPC",cat:"Railway",tag:"POPULAR",q:100,time:"90 min"},
{name:"SSC CGL",cat:"SSC",tag:"POPULAR",q:100,time:"60 min"}
];
const subjects=["Mathematics","Reasoning","General Awareness","Banking Awareness","English","Hindi","Computer","General Science","MP GK"];

function App(){
 const [role,setRole]=useState("student"),[logged,setLogged]=useState(false),[page,setPage]=useState("dashboard"),[open,setOpen]=useState(false),[selected,setSelected]=useState(null);
 if(!logged)return <Landing role={role} setRole={setRole} open={open} setOpen={setOpen} login={()=>setLogged(true)}/>;
 return <Shell role={role} page={page} setPage={setPage} logout={()=>setLogged(false)} selected={selected} setSelected={setSelected}/>;
}

function Brand({dark=false}){return <div className={dark?"brand dark-brand":"brand"}><span className="logo"><Zap size={19} fill="currentColor"/></span><div><b>SKTech Exam Portal</b><small>Prepare Smart. Perform Better.</small></div></div>}

function Landing({role,setRole,open,setOpen,login}){
 return <div className="landing"><header className="topbar"><Brand/><div className="top-actions"><button className="btn ghost" onClick={()=>{setRole("student");setOpen(true)}}>Candidate Login</button><button className="btn dark" onClick={()=>{setRole("admin");setOpen(true)}}>Admin Console</button></div></header>
 <main className="hero"><div className="hero-copy"><span className="pill"><Zap size={13}/> SMART EXAM PREPARATION</span><h1>One portal.<br/><em>Every exam.</em></h1><p>Subject-wise practice, exam-wise mocks, live exams and performance analytics — designed to feel like the real exam.</p><div className="hero-buttons"><button className="btn primary" onClick={()=>{setRole("student");setOpen(true)}}>Start Preparing <ArrowUpRight size={17}/></button><button className="btn light" onClick={()=>{setRole("admin");setOpen(true)}}>Open Admin Console</button></div><div className="trust"><span><ShieldCheck size={16}/> Exam-style interface</span><span><Target size={16}/> Smart performance tracking</span></div></div>
 <div className="hero-card"><div className="hero-card-head"><span>Today’s Practice</span><span className="live-dot">● LIVE</span></div><div className="score">72%<small>overall score <b>↑ 6%</b></small></div><div className="progress"><i style={{width:"72%"}}/></div><div className="metric"><span>Reasoning</span><b>88%</b></div><div className="progress thin"><i style={{width:"88%"}}/></div><div className="metric"><span>Mathematics</span><b>51%</b></div><div className="progress thin"><i style={{width:"51%"}}/></div></div></main>
 <section className="feature-grid">{[[BookOpen,"Subject Practice","Focus on exactly what you need."],[ClipboardCheck,"Real Exam Mocks","Practice with exam-style timing."],[Search,"Latest Vacancies","Official recruitment information."],[Clock3,"Live Countdown","Auto-submit and time tracking."],[Upload,"Bulk Question Upload","TXT, CSV, Excel, PDF & Word."],[BarChart3,"Performance Analytics","Find your weak & strong areas."]].map(([I,x,s])=><div className="feature" key={x}><span className="feature-icon"><I size={18}/></span><b>{x}</b><span>{s}</span></div>)}</section><footer>© 2026 SKTech Exam Portal · Powered by <b>SKTech All Right Reaver</b></footer>{open&&<Login role={role} close={()=>setOpen(false)} login={login}/>}</div>
}

function Login({role,close,login}){const[otp,setOtp]=useState("");return <div className="modal-bg"><div className="modal"><button className="close" onClick={close}><X/></button><Brand/><span className="pill modal-pill">{role==="admin"?"ADMIN CONSOLE":"CANDIDATE PORTAL"}</span><h2>{role==="admin"?"Admin Login":"Welcome back"}</h2><p className="muted">{role==="admin"?"Secure administrator access.":"Login with mobile OTP or Google."}</p><label>{role==="admin"?"Email":"Mobile Number"}</label><input placeholder={role==="admin"?"admin@example.com":"+91 XXXXX XXXXX"}/>{role==="student"?<><button className="btn primary full" onClick={()=>setOtp("")}>Get OTP</button><label>OTP</label><input value={otp} onChange={e=>setOtp(e.target.value)} placeholder="Enter OTP" maxLength={6}/></>:<><label>Password</label><input type="password" placeholder="Admin password"/></>}<button className="btn dark full" onClick={login}>Continue</button>{role==="student"&&<button className="btn google full" onClick={login}>Continue with Google</button>}<small className="muted center">Demo authentication — Supabase will be connected next.</small></div></div>}

function Shell({role,page,setPage,logout,selected,setSelected}){const nav=role==="admin"?[["dashboard","Dashboard",LayoutDashboard],["questions","Question Bank",BookOpen],["exams","Exam Management",ClipboardCheck],["vacancies","Vacancies",Search],["candidates","Candidates",Users],["settings","Settings",Settings]]:[["dashboard","Dashboard",LayoutDashboard],["subjects","Subject Practice",BookOpen],["exams","Mock Tests",ClipboardCheck],["vacancies","Vacancies",Search]];return <div className="app"><aside className="sidebar"><Brand dark/><div className="role-badge">{role==="admin"?"ADMIN CONSOLE":"CANDIDATE PORTAL"}</div>{nav.map(([id,t,I])=><button className={"nav "+(page===id?"active":"")} key={id} onClick={()=>setPage(id)}><I size={18}/>{t}</button>)}<button className="nav logout" onClick={logout}><LogOut size={18}/>Logout</button></aside><div className="main"><header className="dashbar"><button className="hamb"><Menu/></button><div className="welcome"><span className="eyebrow">{role==="admin"?"CONTROL CENTER":"CANDIDATE AREA"}</span><b>{role==="admin"?"Good evening, Admin":"Good evening, Candidate"} <span className="wave">✦</span></b><small>{role==="admin"?"Manage your complete exam ecosystem.":"Keep practicing and improve your score."}</small></div><Profile role={role} logout={logout}/></header><div className="content">{page==="dashboard"&&<Dashboard role={role} setPage={setPage} setSelected={setSelected}/>} {page==="subjects"&&<Subjects setSelected={setSelected}/>} {page==="exams"&&<Exams setSelected={setSelected}/>} {page==="vacancies"&&<Vacancies/>} {page==="questions"&&<Questions/>} {page==="candidates"&&<Candidates/>} {page==="settings"&&<SettingsPage/>}{selected&&<MockModal exam={selected} close={()=>setSelected(null)}/>}</div><footer className="dash-footer">Powered by <b>SKTech All Right Reaver</b></footer></div></div>}

function Profile({role,logout}){const[open,setOpen]=useState(false);return <div className="profile-wrap"><button className="profile-btn" onClick={()=>setOpen(v=>!v)}><span className="avatar">{role==="admin"?"A":"S"}</span><span className="profile-name">{role==="admin"?"Admin":"Candidate"}<small>{role==="admin"?"Administrator":"Student"}</small></span><ChevronDown size={16}/></button>{open&&<div className="profile-menu"><b>{role==="admin"?"Admin Account":"Candidate Account"}</b><button><Users size={15}/> My Profile</button><button><Settings size={15}/> Settings</button><button onClick={logout}><LogOut size={15}/> Logout</button></div>}</div>}

function Title({t,s,action}){return <div className="title"><div><span className="section-kicker">SKTECH EXAM PORTAL</span><h1>{t}</h1><p>{s}</p></div>{action}</div>}

function Dashboard({role,setPage,setSelected}){if(role==="admin")return <><Title t="Admin Dashboard" s="A clean command center for your complete exam platform." action={<button className="btn dark"><CalendarDays size={16}/> 10 Sep 2026</button>}/><div className="stats">{[["Question Bank","12,480","+320 this week",BookOpen],["Candidates","3,842","+126 this week",Users],["Live Exams","4","2 running now",Zap],["Mock Attempts","28,640","+1,240 this week",BarChart3]].map(([a,b,c,I])=><div className="stat" key={a}><div className="stat-icon"><I size={18}/></div><small>{a}</small><strong>{b}</strong><span>{c}</span></div>)}</div><div className="dashboard-grid"><div className="panel highlight-panel"><div className="panel-head"><div><span className="section-kicker">QUICK ACTIONS</span><b>Manage faster</b></div></div><div className="quick">{[[Upload,"Bulk Upload Questions","Add questions in bulk","questions"],[PlusCircle,"Create New Exam","Build an exam","exams"],[Search,"Add Vacancy","Publish vacancy","vacancies"]].map(([I,t,s,p])=><button key={t} onClick={()=>setPage(p)}><span className="quick-icon"><I/></span><span><b>{t}</b><small>{s}</small></span><ArrowUpRight size={16}/></button>)}</div></div><div className="panel"><div className="panel-head"><div><span className="section-kicker">TRENDING NOW</span><b>Popular exams</b></div><button className="text-btn" onClick={()=>setPage("exams")}>View all →</button></div>{exams.slice(0,4).map(e=><ExamRow e={e} onClick={()=>setSelected(e)} key={e.name}/>)}</div></div><div className="panel performance"><div className="panel-head"><div><span className="section-kicker">PLATFORM OVERVIEW</span><b>Activity this week</b></div><span className="success-badge"><CheckCircle2 size={14}/> System healthy</span></div><div className="fake-chart"><div className="chart-bars">{[42,58,51,76,64,88,72].map((h,i)=><i key={i} style={{height:h+"%"}}><span>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</span></i>)}</div></div></div></>;
 return <><Title t="Your Dashboard" s="Your personalised preparation command center." action={<button className="btn primary"><Zap size={16}/> Continue Practice</button>}/><div className="stats">{[["Overall Score","72%","↑ 6% this month",Target],["Tests Completed","38","5 this week",ClipboardCheck],["Strong Subject","Reasoning","88% accuracy",TrendingUp],["Needs Practice","Mathematics","51% accuracy",Target]].map(([a,b,c,I])=><div className="stat" key={a}><div className="stat-icon"><I size={18}/></div><small>{a}</small><strong>{b}</strong><span>{c}</span></div>)}</div><div className="student-grid"><div className="panel focus"><div className="panel-head"><div><span className="section-kicker">RECOMMENDED</span><b>Continue your preparation</b></div><span className="success-badge">72% overall</span></div><div className="focus-body"><div className="focus-copy"><span className="mini-tag">NEXT BEST ACTION</span><h2>Strengthen Mathematics</h2><p>Your recent accuracy is 51%. A focused 25-question practice can improve this quickly.</p><button className="btn dark" onClick={()=>setPage("subjects")}>Start Mathematics Practice <ArrowUpRight size={16}/></button></div><div className="ring"><strong>51%</strong><span>accuracy</span></div></div></div><div className="panel streak"><span className="section-kicker">YOUR STREAK</span><strong>5 days 🔥</strong><p>Keep the momentum going.</p><div className="days">{["M","T","W","T","F","S","S"].map((d,i)=><span className={i<5?"done":""} key={i}>{i<5?<CheckCircle2 size={15}/>:d}</span>)}</div></div></div><Title t="🔥 Trending Exams" s="Exam-style mocks based on current priorities."/><div className="exam-grid">{exams.slice(0,4).map(e=><ExamCard e={e} onClick={()=>setSelected(e)} key={e.name}/>)}</div><Title t="📚 Practice by Subject" s="Focus only on the subject you need."/><div className="subject-grid">{subjects.slice(0,6).map(s=><button className="subject-card" key={s}><span className="subject-dot"/><b>{s}</b><span>Easy · Moderate · Hard <ArrowUpRight size={14}/></span></button>)}</div></>}

function ExamCard({e,onClick}){return <div className="exam-card"><div className="card-top"><span className="tag">{e.tag}</span><span>{e.cat}</span></div><h3>{e.name}</h3><p><FileText size={14}/>{e.q} Questions <Clock3 size={14}/>{e.time}</p><button className="btn dark full" onClick={onClick}>Start Mock <ArrowUpRight size={15}/></button></div>}
function ExamRow({e,onClick}){return <button className="exam-row" onClick={onClick}><div><b>{e.name}</b><small>{e.cat} · {e.q} Questions</small></div><span>Start <ArrowUpRight size={14}/></span></button>}
function Subjects({setSelected}){return <><Title t="📚 Subject Practice" s="Select a subject and difficulty."/><div className="subject-grid all">{subjects.map(s=><div className="subject-card big" key={s}><span className="subject-dot"/><b>{s}</b><span>Easy · Moderate · Hard</span><button className="btn dark" onClick={()=>setSelected({name:s+" Practice",q:25,time:"25 min",cat:"Subject Test"})}>Start Practice</button></div>)}</div></>}
function Exams({setSelected}){return <><Title t="📝 Mock Tests" s="Real-exam style practice with countdown and auto-submit."/><div className="filter"><input placeholder="Search exam..."/><button className="btn light">All Exams</button><button className="btn light">Trending</button></div><div className="exam-grid">{exams.map(e=><ExamCard e={e} onClick={()=>setSelected(e)} key={e.name}/>)}</div></>}
function Vacancies(){return <><Title t="🔎 Latest Vacancies" s="Official recruitment information and direct official links."/><div className="panel vacancy">{exams.map(e=><div className="vac-row" key={e.name}><div><b>{e.name}</b><small>{e.cat} · Check official notification</small></div><a href="https://www.google.com" target="_blank" rel="noreferrer">Official Website ↗</a></div>)}</div></>}
function Questions(){const inputRef=useRef(null);const[file,setFile]=useState(null);return <><Title t="📚 Question Bank" s="Manage and bulk-import questions from your device."/><div className="upload-box" onClick={()=>inputRef.current?.click()}><input ref={inputRef} type="file" hidden accept=".txt,.csv,.xlsx,.xls,.pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="upload-icon"><Upload size={30}/></div><h2>{file?file.name:"Bulk Question Upload"}</h2><p>{file?"File selected. Ready for processing.":"TXT · CSV · XLSX · PDF · DOCX · JPG · PNG"}</p><button className="btn primary" type="button" onClick={e=>{e.stopPropagation();inputRef.current?.click()}}>Choose File</button>{file&&<div className="file-selected"><CheckCircle2 size={16}/> {Math.round(file.size/1024)} KB selected</div>}<small>AI classification: Subject · Topic · Difficulty · Exam mapping · Duplicate check</small></div><div className="panel"><div className="panel-head"><b>Recent Questions</b></div>{["Percentage question","Seating arrangement","RBI monetary policy","MP GK — History"].map((q,i)=><div className="question-row" key={q}><div><b>Q{i+1}</b><small>{q}</small></div><span>AI classified</span></div>)}</div></>}
function Candidates(){return <><Title t="👥 Candidates" s="Monitor registered candidates and activity."/><div className="panel"><div className="candidate-list">{["Candidate One","Candidate Two","Candidate Three","Candidate Four"].map((n,i)=><div className="candidate-row" key={n}><span className="avatar small">{n[0]}</span><div><b>{n}</b><small>{i+1} recent mock attempts</small></div><span className="success-badge">Active</span></div>)}</div></div></>}
function SettingsPage(){return <><Title t="⚙️ Settings" s="Configure portal preferences."/><div className="settings-list"><label>Portal Name<input defaultValue="SKTech Exam Portal"/></label><label>Tagline<input defaultValue="Prepare Smart. Perform Better."/></label><label>Ad Placement<select defaultValue="After login & after exam"><option>After login & after exam</option><option>Dashboard only</option></select></label></div></>}
function MockModal({exam,close}){const[time,setTime]=useState(3599),[q,setQ]=useState(1);useEffect(()=>{const id=setInterval(()=>setTime(t=>Math.max(0,t-1)),1000);return()=>clearInterval(id)},[]);return <div className="modal-bg"><div className="mock"><div className="mock-head"><b>{exam.name}</b><strong><Clock3 size={18}/> {String(Math.floor(time/60)).padStart(2,"0")}:{String(time%60).padStart(2,"0")}</strong></div><div className="mock-body"><main><span className="pill">QUESTION {q}</span><h2>Which of the following is the correct answer for this demo question?</h2>{["Option A","Option B","Option C","Option D"].map(x=><label className="option" key={x}><input type="radio" name="q"/>{x}</label>)}<div className="mock-actions"><button className="btn light" onClick={()=>setQ(Math.max(1,q-1))}>Previous</button><button className="btn light">Mark for Review</button><button className="btn dark" onClick={()=>setQ(q+1)}>Save & Next</button></div></main><aside><b>Question Palette</b><div className="palette">{Array.from({length:Math.min(exam.q||25,30)},(_,i)=><button className={i+1===q?"sel":""} onClick={()=>setQ(i+1)} key={i}>{i+1}</button>)}</div><button className="btn primary full" onClick={close}>Submit Demo</button></aside></div></div></div>}
createRoot(document.getElementById("root")).render(<App/>);
